version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  Api1:
    build:
      context: .
      dockerfile: Dockerfile
    image: restapi:v1.0.0
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      migration:
        condition: service_started
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: 8001
    ports:
      - "8001:8001"
    networks:
      - app-network

  Api2:
    image: restapi:v1.0.0
    depends_on:
      Api1:
        condition: service_started
      postgres:
        condition: service_healthy
        restart: true
      migration:
        condition: service_started
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: 8002
    ports:
      - "8002:8002"
    networks:
      - app-network

  nginx:
    image: nginx:1.29.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      Api1:
        condition: service_started
      Api2:
        condition: service_started
    networks:
      - app-network

  migration:
    image: restapi:v1.0.0
    environment:
      PYWAY_TYPE: "postgres"
      PYWAY_TABLE: "pyway_schema_history"
      PYWAY_DATABASE_HOST: ${POSTGRES_HOST}
      PYWAY_DATABASE_NAME: ${POSTGRES_DB}
      PYWAY_DATABASE_USERNAME: ${POSTGRES_USER}
      PYWAY_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      PYWAY_DATABASE_PORT: ${POSTGRES_PORT} 
      PYWAY_DATABASE_MIGRATION_DIR: "/app/migrations"
    depends_on:
      DB:
        condition: service_healthy
    command: >
      sh -c "
        pyway migrate
        pyway info
      "
    networks:
      - app-network

  postgres:
    image: postgres:17.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data: